{"name": "test_login_empty_input", "status": "broken", "statusDetails": {"message": "KeyError: '9166d19b-02ef-4930-9bf1-a442d8a2fc6d'", "trace": "self = <pages.register_page.RegisterPage object at 0x106236350>, locator = ('xpath', \"//*[contains(@resource-id,'tv_login')]\"), timeout = 25, return_bool = False\n\n    @allure.step\n    def find_element_and_click(self, locator, timeout=25, return_bool=False):\n        \"\"\"\n        Purpose:\n            find element based on locator, make sure element is clickable, and click the element.\n        Args:\n            locator (e.g. AndroidLocators.DEFAULT_ANDROID_POPOVER_OK_BUTTON)\n            (optional) timeout (int): How much time to wait before exception; default is 10 seconds\n            (optional) return_bool (bool): Return bool instead of assertionError; default is False\n        Returns:\n            either bool or None depends on return_bool option\n        \"\"\"\n        # this decides whether to fail the test if the element can't be found\n        function_will_return_boolean = return_bool\n        el = None\n        try:\n>           el = WebDriverWait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n\npages/base_pages.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"42a39934eb11416f2f3b02090aff3a77236bc4e1\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x106208f70>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       NoSuchElementError: An element could not be located on the page using the given search parameters.\nE           at AndroidUiautomator2Driver.findElOrEls (/nix/store/a4f03fnyb1njsg95d11hrirds8hfjsc1-appium-1.17.0/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:90: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\na = (<pages.register_page.RegisterPage object at 0x106236350>, ('xpath', \"//*[contains(@resource-id,'tv_login')]\")), kw = {}, __tracebackhide__ = True\nparams = OrderedDict([('locator', '(\\'xpath\\', \"//*[contains(@resource-id,\\'tv_login\\')]\")'), ('timeout', '25'), ('return_bool', 'False')])\nargs = ['<pages.register_page.RegisterPage object at 0x106236350>', '(\\'xpath\\', \"//*[contains(@resource-id,\\'tv_login\\')]\")']\n\n    @wraps(func)\n    def impl(*a, **kw):\n        __tracebackhide__ = True\n        params = func_parameters(func, *a, **kw)\n        args = list(map(lambda x: represent(x), a))\n        with StepContext(self.title.format(*args, **params), params):\n>           return func(*a, **kw)\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py:180: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.register_page.RegisterPage object at 0x106236350>, locator = ('xpath', \"//*[contains(@resource-id,'tv_login')]\"), timeout = 25, return_bool = False\n\n    @allure.step\n    def find_element_and_click(self, locator, timeout=25, return_bool=False):\n        \"\"\"\n        Purpose:\n            find element based on locator, make sure element is clickable, and click the element.\n        Args:\n            locator (e.g. AndroidLocators.DEFAULT_ANDROID_POPOVER_OK_BUTTON)\n            (optional) timeout (int): How much time to wait before exception; default is 10 seconds\n            (optional) return_bool (bool): Return bool instead of assertionError; default is False\n        Returns:\n            either bool or None depends on return_bool option\n        \"\"\"\n        # this decides whether to fail the test if the element can't be found\n        function_will_return_boolean = return_bool\n        el = None\n        try:\n            el = WebDriverWait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n        except TimeoutException:\n            if function_will_return_boolean:\n                return False\n            else:\n>               assert el is not None, 'element->{0} can\\'t be found in find_element_and_click'.format(str(locator))\nE               AssertionError: element->('xpath', \"//*[contains(@resource-id,'tv_login')]\") can't be found in find_element_and_click\n\npages/base_pages.py:39: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\na = (<pages.register_page.RegisterPage object at 0x106236350>,), kw = {}, __tracebackhide__ = True, params = OrderedDict()\nargs = ['<pages.register_page.RegisterPage object at 0x106236350>']\n\n    @wraps(func)\n    def impl(*a, **kw):\n        __tracebackhide__ = True\n        params = func_parameters(func, *a, **kw)\n        args = list(map(lambda x: represent(x), a))\n        with StepContext(self.title.format(*args, **params), params):\n>           return func(*a, **kw)\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py:180: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.register_page.RegisterPage object at 0x106236350>\n\n    @allure.step(\"And user click login button\")\n    def click_login_button(self):\n>       self.find_element_and_click(RegisterPageLocators.LOGIN_BUTTON)\n\npages/register_page.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\na = (<pages.register_page.RegisterPage object at 0x106236350>, ('xpath', \"//*[contains(@resource-id,'tv_login')]\")), kw = {}, __tracebackhide__ = True\nparams = OrderedDict([('locator', '(\\'xpath\\', \"//*[contains(@resource-id,\\'tv_login\\')]\")'), ('timeout', '25'), ('return_bool', 'False')])\nargs = ['<pages.register_page.RegisterPage object at 0x106236350>', '(\\'xpath\\', \"//*[contains(@resource-id,\\'tv_login\\')]\")']\n\n    @wraps(func)\n    def impl(*a, **kw):\n        __tracebackhide__ = True\n        params = func_parameters(func, *a, **kw)\n        args = list(map(lambda x: represent(x), a))\n>       with StepContext(self.title.format(*args, **params), params):\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py:179: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_commons._allure.StepContext object at 0x106235d20>, exc_type = <class 'AssertionError'>\nexc_val = AssertionError('element->(\\'xpath\\', \"//*[contains(@resource-id,\\'tv_login\\')]\") can\\'t be found in find_element_and_click'), exc_tb = <traceback object at 0x106257d80>\n\n    def __exit__(self, exc_type, exc_val, exc_tb):\n>       plugin_manager.hook.stop_step(uuid=self.uuid, title=self.title, exc_type=exc_type, exc_val=exc_val,\n                                      exc_tb=exc_tb)\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py:170: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <_HookCaller 'stop_step'>, args = ()\nkwargs = {'exc_tb': <traceback object at 0x106257d80>, 'exc_type': <class 'AssertionError'>, 'exc_val': AssertionError('element...ains(@resource-id,\\'tv_login\\')]\") can\\'t be found in find_element_and_click'), 'title': 'find_element_and_click', ...}\nargname = 'exc_tb', firstresult = False\n\n    def __call__(self, *args, **kwargs):\n        if args:\n            raise TypeError(\"hook calling supports only keyword arguments\")\n        assert not self.is_historic()\n    \n        # This is written to avoid expensive operations when not needed.\n        if self.spec:\n            for argname in self.spec.argnames:\n                if argname not in kwargs:\n                    notincall = tuple(set(self.spec.argnames) - kwargs.keys())\n                    warnings.warn(\n                        \"Argument(s) {} which are declared in the hookspec \"\n                        \"can not be found in this hook call\".format(notincall),\n                        stacklevel=2,\n                    )\n                    break\n    \n            firstresult = self.spec.opts.get(\"firstresult\")\n        else:\n            firstresult = False\n    \n>       return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_hooks.py:265: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pluggy._manager.PluginManager object at 0x105cf34c0>, hook_name = 'stop_step'\nmethods = [<HookImpl plugin_name='4395519760', plugin=<allure_pytest.listener.AllureListener object at 0x105fe4f10>>, <HookImpl ...105fe45e0>>, <HookImpl plugin_name='4393737936', plugin=<allure_pytest.listener.AllureListener object at 0x105e31ed0>>]\nkwargs = {'exc_tb': <traceback object at 0x106257d80>, 'exc_type': <class 'AssertionError'>, 'exc_val': AssertionError('element...ains(@resource-id,\\'tv_login\\')]\") can\\'t be found in find_element_and_click'), 'title': 'find_element_and_click', ...}\nfirstresult = False\n\n    def _hookexec(self, hook_name, methods, kwargs, firstresult):\n        # called from all hookcaller instances.\n        # enable_tracing will set its own wrapping function at self._inner_hookexec\n>       return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_manager.py:80: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nhook_name = 'stop_step'\nhook_impls = [<HookImpl plugin_name='4395519760', plugin=<allure_pytest.listener.AllureListener object at 0x105fe4f10>>, <HookImpl ...105fe45e0>>, <HookImpl plugin_name='4393737936', plugin=<allure_pytest.listener.AllureListener object at 0x105e31ed0>>]\ncaller_kwargs = {'exc_tb': <traceback object at 0x106257d80>, 'exc_type': <class 'AssertionError'>, 'exc_val': AssertionError('element...ains(@resource-id,\\'tv_login\\')]\") can\\'t be found in find_element_and_click'), 'title': 'find_element_and_click', ...}\nfirstresult = False\n\n    def _multicall(hook_name, hook_impls, caller_kwargs, firstresult):\n        \"\"\"Execute a call into multiple python functions/methods and return the\n        result(s).\n    \n        ``caller_kwargs`` comes from _HookCaller.__call__().\n        \"\"\"\n        __tracebackhide__ = True\n        results = []\n        excinfo = None\n        try:  # run impl and wrapper setup functions in a loop\n            teardowns = []\n            try:\n                for hook_impl in reversed(hook_impls):\n                    try:\n                        args = [caller_kwargs[argname] for argname in hook_impl.argnames]\n                    except KeyError:\n                        for argname in hook_impl.argnames:\n                            if argname not in caller_kwargs:\n                                raise HookCallError(\n                                    f\"hook call must provide argument {argname!r}\"\n                                )\n    \n                    if hook_impl.hookwrapper:\n                        try:\n                            gen = hook_impl.function(*args)\n                            next(gen)  # first yield\n                            teardowns.append(gen)\n                        except StopIteration:\n                            _raise_wrapfail(gen, \"did not yield\")\n                    else:\n                        res = hook_impl.function(*args)\n                        if res is not None:\n                            results.append(res)\n                            if firstresult:  # halt further impl calls\n                                break\n            except BaseException:\n                excinfo = sys.exc_info()\n        finally:\n            if firstresult:  # first result hooks return a single value\n                outcome = _Result(results[0] if results else None, excinfo)\n            else:\n                outcome = _Result(results, excinfo)\n    \n            # run all wrapper post-yield blocks\n            for gen in reversed(teardowns):\n                try:\n                    gen.send(outcome)\n                    _raise_wrapfail(gen, \"has second yield\")\n                except StopIteration:\n                    pass\n    \n>           return outcome.get_result()\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_callers.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pluggy._result._Result object at 0x106236800>\n\n    def get_result(self):\n        \"\"\"Get the result(s) for this hook call.\n    \n        If the hook was marked as a ``firstresult`` only a single value\n        will be returned otherwise a list of results.\n        \"\"\"\n        __tracebackhide__ = True\n        if self._excinfo is None:\n            return self._result\n        else:\n            ex = self._excinfo\n>           raise ex[1].with_traceback(ex[2])\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_result.py:60: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nhook_name = 'stop_step'\nhook_impls = [<HookImpl plugin_name='4395519760', plugin=<allure_pytest.listener.AllureListener object at 0x105fe4f10>>, <HookImpl ...105fe45e0>>, <HookImpl plugin_name='4393737936', plugin=<allure_pytest.listener.AllureListener object at 0x105e31ed0>>]\ncaller_kwargs = {'exc_tb': <traceback object at 0x106257d80>, 'exc_type': <class 'AssertionError'>, 'exc_val': AssertionError('element...ains(@resource-id,\\'tv_login\\')]\") can\\'t be found in find_element_and_click'), 'title': 'find_element_and_click', ...}\nfirstresult = False\n\n    def _multicall(hook_name, hook_impls, caller_kwargs, firstresult):\n        \"\"\"Execute a call into multiple python functions/methods and return the\n        result(s).\n    \n        ``caller_kwargs`` comes from _HookCaller.__call__().\n        \"\"\"\n        __tracebackhide__ = True\n        results = []\n        excinfo = None\n        try:  # run impl and wrapper setup functions in a loop\n            teardowns = []\n            try:\n                for hook_impl in reversed(hook_impls):\n                    try:\n                        args = [caller_kwargs[argname] for argname in hook_impl.argnames]\n                    except KeyError:\n                        for argname in hook_impl.argnames:\n                            if argname not in caller_kwargs:\n                                raise HookCallError(\n                                    f\"hook call must provide argument {argname!r}\"\n                                )\n    \n                    if hook_impl.hookwrapper:\n                        try:\n                            gen = hook_impl.function(*args)\n                            next(gen)  # first yield\n                            teardowns.append(gen)\n                        except StopIteration:\n                            _raise_wrapfail(gen, \"did not yield\")\n                    else:\n>                       res = hook_impl.function(*args)\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_callers.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_pytest.listener.AllureListener object at 0x105fe45e0>, uuid = '65be56c1-46db-4da1-8b8e-b52953308393', exc_type = <class 'AssertionError'>\nexc_val = AssertionError('element->(\\'xpath\\', \"//*[contains(@resource-id,\\'tv_login\\')]\") can\\'t be found in find_element_and_click'), exc_tb = <traceback object at 0x106257d80>\n\n    @allure_commons.hookimpl\n    def stop_step(self, uuid, exc_type, exc_val, exc_tb):\n>       self.allure_logger.stop_step(uuid,\n                                     stop=now(),\n                                     status=get_status(exc_val),\n                                     statusDetails=get_status_details(exc_type, exc_val, exc_tb))\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_pytest/listener.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_commons.reporter.AllureReporter object at 0x105ea1420>, uuid = '65be56c1-46db-4da1-8b8e-b52953308393'\nkwargs = {'status': 'failed', 'statusDetails': StatusDetails(known=None, flaky=None, message='AssertionError: element->(\\'xpath...not None, \\'element->{0} can\\\\\\'t be found in find_element_and_click\\'.format(str(locator))\\n'), 'stop': 1693145949228}\n\n    def stop_step(self, uuid, **kwargs):\n        if uuid in self._orphan_items:\n            self._orphan_items.remove(uuid)\n        else:\n>           self._update_item(uuid, **kwargs)\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/reporter.py:139: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_commons.reporter.AllureReporter object at 0x105ea1420>, uuid = '65be56c1-46db-4da1-8b8e-b52953308393'\nkwargs = {'status': 'failed', 'statusDetails': StatusDetails(known=None, flaky=None, message='AssertionError: element->(\\'xpath...not None, \\'element->{0} can\\\\\\'t be found in find_element_and_click\\'.format(str(locator))\\n'), 'stop': 1693145949228}\n\n    def _update_item(self, uuid, **kwargs):\n>       item = self._items[uuid] if uuid else self._items[next(reversed(self._items))]\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/reporter.py:62: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_commons.reporter.ThreadContextItems object at 0x105ea1b10>, item = '65be56c1-46db-4da1-8b8e-b52953308393'\n\n    def __getitem__(self, item):\n>       return self.thread_context.__getitem__(item)\nE       KeyError: '65be56c1-46db-4da1-8b8e-b52953308393'\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/reporter.py:33: KeyError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_login.TestLogin object at 0x10612ee60>, driver = <appium.webdriver.webdriver.WebDriver (session=\"42a39934eb11416f2f3b02090aff3a77236bc4e1\")>\n\n    @pytest.mark.login_negative\n    def test_login_empty_input(self, driver):\n        # Initialization\n        self.init(driver)\n    \n        # The User click on Login button\n>       self.register_page.click_login_button()\n\ntests/test_login.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py:170: in __exit__\n    plugin_manager.hook.stop_step(uuid=self.uuid, title=self.title, exc_type=exc_type, exc_val=exc_val,\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_pytest/listener.py:44: in stop_step\n    self.allure_logger.stop_step(uuid,\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/reporter.py:139: in stop_step\n    self._update_item(uuid, **kwargs)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/reporter.py:62: in _update_item\n    item = self._items[uuid] if uuid else self._items[next(reversed(self._items))]\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_commons.reporter.ThreadContextItems object at 0x105ea1b10>, item = '9166d19b-02ef-4930-9bf1-a442d8a2fc6d'\n\n    def __getitem__(self, item):\n>       return self.thread_context.__getitem__(item)\nE       KeyError: '9166d19b-02ef-4930-9bf1-a442d8a2fc6d'\n\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/reporter.py:33: KeyError"}, "steps": [{"name": "And user click login button", "steps": [{"name": "And user click login button", "steps": [{"name": "And user click login button", "status": "broken", "statusDetails": {"message": "KeyError: '65be56c1-46db-4da1-8b8e-b52953308393'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 180, in impl\n    return func(*a, **kw)\n  File \"/Users/yaroslav.petryk/Desktop/projects/browserstack_appium/pages/register_page.py\", line 24, in click_login_button\n    self.find_element_and_click(RegisterPageLocators.LOGIN_BUTTON)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 179, in impl\n    with StepContext(self.title.format(*args, **params), params):\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 170, in __exit__\n    plugin_manager.hook.stop_step(uuid=self.uuid, title=self.title, exc_type=exc_type, exc_val=exc_val,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_pytest/listener.py\", line 44, in stop_step\n    self.allure_logger.stop_step(uuid,\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/reporter.py\", line 139, in stop_step\n    self._update_item(uuid, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/reporter.py\", line 62, in _update_item\n    item = self._items[uuid] if uuid else self._items[next(reversed(self._items))]\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/reporter.py\", line 33, in __getitem__\n    return self.thread_context.__getitem__(item)\n"}, "steps": [{"name": "find_element_and_click", "steps": [{"name": "find_element_and_click", "steps": [{"name": "find_element_and_click", "status": "failed", "statusDetails": {"message": "AssertionError: element->('xpath', \"//*[contains(@resource-id,'tv_login')]\") can't be found in find_element_and_click\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 180, in impl\n    return func(*a, **kw)\n  File \"/Users/yaroslav.petryk/Desktop/projects/browserstack_appium/pages/base_pages.py\", line 39, in find_element_and_click\n    assert el is not None, 'element->{0} can\\'t be found in find_element_and_click'.format(str(locator))\n"}, "parameters": [{"name": "locator", "value": "('xpath', \"//*[contains(@resource-id,'tv_login')]\")"}, {"name": "timeout", "value": "25"}, {"name": "return_bool", "value": "False"}], "start": 1693145923768, "stop": 1693145949196}], "parameters": [{"name": "locator", "value": "('xpath', \"//*[contains(@resource-id,'tv_login')]\")"}, {"name": "timeout", "value": "25"}, {"name": "return_bool", "value": "False"}], "start": 1693145923768}], "parameters": [{"name": "locator", "value": "('xpath', \"//*[contains(@resource-id,'tv_login')]\")"}, {"name": "timeout", "value": "25"}, {"name": "return_bool", "value": "False"}], "start": 1693145923768}], "start": 1693145923768, "stop": 1693145949229}], "start": 1693145923768}], "start": 1693145923768}], "attachments": [{"name": "log", "source": "2dabb558-776b-419b-9b63-b74316d4ee2d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "b7bd5f44-40dc-4c8a-8116-6a255d55ee47-attachment.txt", "type": "text/plain"}], "start": 1693145921280, "stop": 1693145949269, "uuid": "44ebd71c-d735-46e0-b34f-5f7dc24a9584", "historyId": "05603206456e4809964169438552e439", "testCaseId": "f352a75c52f7b26ebfd83a491ec0fff9", "fullName": "tests.test_login.TestLogin#test_login_empty_input", "labels": [{"name": "tag", "value": "login_negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ypetryk-MacBook-Pro.local"}, {"name": "thread", "value": "3260-2"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}